### ISSUE TITLE
GodotAndroidDeeplinkPlugin singleton not found!

### ISSUE THREAD

**Issue by nguyentuanit97** [cengiz-pz/godot-android-deeplink-plugin#1] opened 2024-05-07 09:12 UTC
<img width="516" alt="Screenshot 2024-05-07 at 16 10 01" src="https://github.com/cengiz-pz/godot-android-deeplink-plugin/assets/38986433/541c2646-ab53-428b-884a-7f80b761a9b3">

Following the instructions, I installed Installing via AssetLib. But got the issue: "GodotAndroidDeeplinkPlugin singleton not found!".

I also pull the example project and install like that but still have issues like that. Where did I go wrong?

I'm using Godot v4.2.1.

**Comment by cengiz-pz** [comment] 2024-05-07 15:40
Hi @nguyentuanit97, are you running your app on an Android device?

**Comment by nguyentuanit97** [comment] 2024-05-08 06:33
Hi @cengiz-pz , thanks for your reply.

Yes. It showing that error but it's still working actually.

Yes I'm running on Android devices. It seems working really well on chrome browser.

But for some default browser of some devices, it's seems not stable yet. 
For example, 
- In default browser of xiaomi I don't see any button to deeplink back to app (seems not working)
- In samsung, I only see a small icon app next to the search typing bar. I have to click on the app icon to navigate my app again. When the app is in background mode, my app will crash

If you need me provide image/record video to reproduce, please let me know. 
Also, thank you for this great plugin. It has helped me a lot.

**Comment by cengiz-pz** [comment] 2024-05-08 15:15
Hi @nguyentuanit97, sure video would be fine but a minimal app where the problem is reproducible would be even better.  I won't be able to look into it this week; hopefully next week.

**Comment by cengiz-pz** [comment] 2024-11-16 15:20
Closing this as no further information was provided.

**Closed by cengiz-pz** 2024-11-16 15:20 UTC
